//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWRMedical
{


    public partial class SuccessStories {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GWRMedical.SiteMaster Master {
            get {
                return ((GWRMedical.SiteMaster)(base.Master));
            }
        }
    }
}
